### PR TITLE
add tests for new vs logic

### PR DESCRIPTION
**Pull request by msarahan**
This is as far as I could get tonight.  These tests do not run for me - I'm stuck at a windows permission error on creating the SDK dir, as I do not have it installed.  I'll pick up tomorrow.

The general idea is to hide all possible bat files, then replace them with a set of dummy bat files.  Only one of the dummies will succeed.  If it does the right one, then the test passes.  Parameterization is done to make the tests compact.

### CODE REVIEW

**Comment by msarahan** [comment]
This is now working pretty well.  One major caveat: you must run these tests from an administrator prompt.  You get permissions errors otherwise.  These are tests that should probably not be run on AppVeyor as a result - but hopefully useful for manual verification.

**Comment by jankatins** [comment]
Maybe add these tests to a special file which is only run on a different instance/configuration? AFAIK you have admin rights on appveyor, at least copying the files to the right places worked for matplotlib as a workaround.

**Comment by msarahan** [comment]
AFAIK (on my own system), even with UAC disabled, I still can't create folders in C:\Program Files\ as an administrator without an elevated prompt.  I would be so, so happy to be proven wrong, though.  This would be a nice test to add to conda build.

**Comment by jankatins** [comment]
mpl at least copies files to such dirs: https://github.com/matplotlib/matplotlib/blob/master/appveyor.yml#L65

I suspect that UAC is disabled in the appveyor VMs.

**Comment by patricksnape** [comment]
Awesome work, thanks so much @msarahan! If we wanted to try running this on Appveyor - how do we go about it? Going to merge this so we can keep any discussions about it on the other PR.

**Comment by jankatins** [comment]
If you want to do in in your repo:
- get an account on appveyor (login with your github account)
- activate the repo there
- add a appveyor.yml file which calls the tests (similar to travis.yml, but different syntax...)
- add a commit to the branch to trigger the build

**Pull request merged**
